// The Daily Bit — puzzle pool (40 entries: 18 quiz, 14 fix, 8 bits).
// Every quiz output and every fix starter/solution verified by compiling
// and running on godbolt.org (gcc 15.1, x86-64).
window.DAILY_POOL = [
  {
    type: "quiz",
    title: "Walk the line",
    code: "#include <stdio.h>\n\nint main(void) {\n    int a[] = {10, 20, 30};\n    int *p = a;\n    p++;\n    printf(\"%d\\n\", *p + 1);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["11", "31", "20", "21"],
    a: 3,
    expl: "<p><code>p</code> starts at the first element, and <code>p++</code> moves it one whole <code>int</code> forward — pointer arithmetic works in elements, not bytes. So <code>*p</code> is 20, and adding 1 gives 21.</p>",
  },
  {
    type: "fix",
    title: "Factorial fizzle",
    brief: "5! is 120 — but this prints 24. Fix it.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int fact = 1;\n    for (int i = 1; i < 5; i++)\n        fact *= i;\n    printf(\"%d\\n\", fact);\n    return 0;\n}",
    expect: "120\n",
    hint: "How many times does the loop body actually run?",
    expl: "<p>With <code>i &lt; 5</code> the loop multiplies 1·2·3·4 and stops before the 5. Changing the condition to <code>i &lt;= 5</code> includes the final factor: 24 · 5 = 120.</p>",
  },
  {
    type: "bits",
    title: "The answer",
    target: 0x2A,
    n: 8,
    brief: "Flip the bits until the byte equals 42 (0x2A).",
    hint: "42 = 32 + 8 + 2",
    expl: "<p>42 is 0010 1010 in binary: bits 5, 3 and 1 are set (32 + 8 + 2). Read nibble by nibble, 0010 is 2 and 1010 is A — hence 0x2A.</p>",
  },
  {
    type: "quiz",
    title: "Sizing them up",
    code: "#include <stdio.h>\n\nint main(void) {\n    if (-1 < 1u)\n        printf(\"yes\\n\");\n    else\n        printf(\"no\\n\");\n    return 0;\n}",
    q: "What does this print?",
    opts: ["yes", "no", "compile error", "undefined behavior"],
    a: 1,
    expl: "<p>When an <code>int</code> meets an <code>unsigned int</code>, the usual arithmetic conversions turn the <code>int</code> into unsigned — so -1 becomes 4294967295. That giant value is not less than 1, and the else branch runs. Mixing signed and unsigned in comparisons is a classic trap.</p>",
  },
  {
    type: "fix",
    title: "Case in point",
    brief: "day is 2, so it should print only Tue — but Wed tags along.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int day = 2;\n    switch (day) {\n    case 1:\n        printf(\"Mon\\n\");\n        break;\n    case 2:\n        printf(\"Tue\\n\");\n    case 3:\n        printf(\"Wed\\n\");\n    }\n    return 0;\n}",
    expect: "Tue\n",
    hint: "What stops a switch from running into the next case?",
    expl: "<p>Without <code>break</code>, control falls straight through from <code>case 2</code> into <code>case 3</code>. Adding <code>break;</code> after printing Tue leaves the switch. Fall-through is occasionally useful — but only when you mean it.</p>",
  },
  {
    type: "quiz",
    title: "Split decision",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%d\\n\", 7 / 2);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["3.5", "4", "3", "compile error"],
    a: 2,
    expl: "<p>Both operands are <code>int</code>, so <code>/</code> performs integer division and drops the remainder: 7 / 2 is 3, not 3.5. To get 3.5 you would need a floating-point operand, like <code>7.0 / 2</code>.</p>",
  },
  {
    type: "bits",
    title: "Nibble practice",
    target: 0x05,
    n: 4,
    brief: "Flip the bits until the nibble equals 0x5.",
    hint: "5 = 4 + 1",
    expl: "<p>0101 — bit 2 (worth 4) and bit 0 (worth 1). One hex digit is exactly one 4-bit nibble, which is why hex and binary translate so cleanly.</p>",
  },
  {
    type: "fix",
    title: "Point taken",
    brief: "It should print the sum of the coordinates, 7 — but it doesn't even compile.",
    code: "#include <stdio.h>\n\nstruct Point {\n    int x;\n    int y;\n};\n\nint main(void) {\n    struct Point pt = {3, 4};\n    struct Point *p = &pt;\n    printf(\"%d\\n\", p.x + p.y);\n    return 0;\n}",
    expect: "7\n",
    hint: "p is a pointer to the struct, not the struct itself.",
    expl: "<p><code>p</code> is a <code>struct Point *</code>, so its members are reached with the arrow operator: <code>p-&gt;x + p-&gt;y</code>. The dot operator only works on the struct value itself, like <code>pt.x</code>.</p>",
  },
  {
    type: "quiz",
    title: "Self service",
    code: "#include <stdio.h>\n\nint main(void) {\n    int i = 0;\n    i = i++ + 1;\n    printf(\"%d\\n\", i);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["1", "2", "0", "undefined behavior"],
    a: 3,
    expl: "<p>The assignment writes to <code>i</code>, and <code>i++</code> also writes to <code>i</code> — two side effects on the same object with no sequencing between them, which C17 (6.5p2) declares undefined behavior. Any output, or none, would be a legal outcome. Never combine <code>++</code> with another write to the same variable in one expression.</p>",
  },
  {
    type: "fix",
    title: "Speechless",
    brief: "It should greet the world — but it won't even compile.",
    code: "int main(void) {\n    printf(\"Hello, world\\n\");\n    return 0;\n}",
    expect: "Hello, world\n",
    hint: "printf is not a keyword — where does it come from?",
    expl: "<p><code>printf</code> lives in the standard library, and calling a function with no declaration in sight is an error in modern C. Adding <code>#include &lt;stdio.h&gt;</code> at the top brings in its declaration.</p>",
  },
  {
    type: "quiz",
    title: "Struck by lightning",
    code: "#include <stdio.h>\n\nstruct Point {\n    int x;\n    int y;\n};\n\nint main(void) {\n    struct Point p = {1};\n    printf(\"%d %d\\n\", p.x, p.y);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["1 0", "1 then garbage", "compile error", "0 0"],
    a: 0,
    expl: "<p>An initializer list may supply fewer values than there are members — the remaining members are set to zero, exactly as if they had static storage. So <code>x</code> is 1 and <code>y</code> is 0: no garbage, no error.</p>",
  },
  {
    type: "bits",
    title: "Lights on",
    target: 0xFF,
    n: 8,
    brief: "Turn the byte into 0xFF.",
    hint: "Every single bit.",
    expl: "<p>1111 1111 is 255, or 2<sup>8</sup> − 1 — the largest value a byte can hold. As a mask, <code>x &amp; 0xFF</code> keeps just the low 8 bits of any value.</p>",
  },
  {
    type: "fix",
    title: "Double or nothing",
    brief: "DOUBLE(1 + 2) should be 6 — but this prints 4.",
    code: "#include <stdio.h>\n\n#define DOUBLE(x) 2 * x\n\nint main(void) {\n    printf(\"%d\\n\", DOUBLE(1 + 2));\n    return 0;\n}",
    expect: "6\n",
    hint: "Write out exactly what the preprocessor pastes in.",
    expl: "<p>Macros paste text: the call expands to <code>2 * 1 + 2</code>, and multiplication binds first, giving 4. Parenthesizing the parameter — <code>#define DOUBLE(x) 2 * (x)</code> — keeps the argument in one piece. Always parenthesize macro parameters.</p>",
  },
  {
    type: "quiz",
    title: "Shifty business",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%d\\n\", 1 << 2 + 1);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["8", "5", "3", "4"],
    a: 0,
    expl: "<p>Addition binds tighter than shifts, so this is <code>1 &lt;&lt; (2 + 1)</code>, i.e. 1 shifted left 3 places: 8. If you expected <code>(1 &lt;&lt; 2) + 1</code> = 5, that is exactly why shift expressions deserve parentheses.</p>",
  },
  {
    type: "fix",
    title: "Trading places",
    brief: "Swap x and y — it should print 2 1, but prints 2 2.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int x = 1, y = 2;\n    int t = x;\n    x = y;\n    y = x;\n    printf(\"%d %d\\n\", x, y);\n    return 0;\n}",
    expect: "2 1\n",
    hint: "What was t saved for?",
    expl: "<p>After <code>x = y</code>, the original value of <code>x</code> is gone — it survives only in <code>t</code>. The last step must be <code>y = t;</code> to complete the classic three-step swap.</p>",
  },
  {
    type: "quiz",
    title: "Special delivery",
    code: "#include <stdio.h>\n\nvoid measure(int a[10]) {\n    printf(\"%zu\\n\", sizeof a);\n}\n\nint main(void) {\n    int nums[10];\n    measure(nums);\n    return 0;\n}",
    q: "What does this print (on a typical 64-bit system)?",
    opts: ["40", "10", "8", "compile error"],
    a: 2,
    expl: "<p>An array parameter is really a pointer — the <code>[10]</code> is decoration. Inside the function, <code>sizeof a</code> is the size of an <code>int *</code>: 8 bytes on a 64-bit system, not the array's 40. That is why C functions take the length as a separate argument.</p>",
  },
  {
    type: "bits",
    title: "Century mark",
    target: 0x64,
    n: 8,
    brief: "Make the byte equal 100 (0x64).",
    hint: "100 = 64 + 32 + 4",
    expl: "<p>0110 0100 — bits 6, 5 and 2. In hex that is 0x64, a fun coincidence: decimal 100 written in hex looks like \"64\".</p>",
  },
  {
    type: "fix",
    title: "The generous if",
    brief: "x is 0, so it should print zero — but it prints nonzero.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int x = 0;\n    if (x = 0)\n        printf(\"zero\\n\");\n    else\n        printf(\"nonzero\\n\");\n    return 0;\n}",
    expect: "zero\n",
    hint: "Look very closely at the condition.",
    expl: "<p><code>x = 0</code> is an assignment; its value is 0, so the condition is always false. Comparison is <code>==</code>. Compilers warn about this with warnings enabled, and some programmers write <code>0 == x</code> so the typo cannot even compile.</p>",
  },
  {
    type: "quiz",
    title: "Measuring tape",
    code: "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char s[] = \"hello\";\n    printf(\"%zu %zu\\n\", sizeof s, strlen(s));\n    return 0;\n}",
    q: "What does this print?",
    opts: ["5 5", "8 5", "6 5", "5 6"],
    a: 2,
    expl: "<p><code>sizeof s</code> measures the whole array: five letters plus the terminating <code>'\\0'</code>, so 6. <code>strlen</code> counts characters up to — not including — that terminator, so 5.</p>",
  },
  {
    type: "fix",
    title: "Power trip",
    brief: "2 to the power 3 is 8 — but this prints 1.",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%d\\n\", 2 ^ 3);\n    return 0;\n}",
    expect: "8\n",
    hint: "C has no exponent operator.",
    expl: "<p><code>^</code> is bitwise XOR, not exponentiation: 10 XOR 11 is 01, which is 1. Compute powers with <code>pow()</code> from math.h, a loop like <code>2 * 2 * 2</code>, or <code>1 &lt;&lt; 3</code> for powers of two.</p>",
  },
  {
    type: "quiz",
    title: "Mixed signals",
    code: "#include <stdio.h>\n\nint main(void) {\n    double d = 1 / 2 + 0.5;\n    printf(\"%.1f\\n\", d);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["1.0", "0.0", "0.5", "compile error"],
    a: 2,
    expl: "<p>The int-vs-float decision is made per operator, not per statement: <code>1 / 2</code> is pure integer division, giving 0, and only then is the double 0.5 added. Writing <code>1.0 / 2</code> would give 1.0 instead.</p>",
  },
  {
    type: "bits",
    title: "The loner",
    target: 0x80,
    n: 8,
    brief: "Light exactly the right bit to make 0x80.",
    hint: "One bit, worth 128.",
    expl: "<p>1000 0000 — only the most significant bit, worth 2<sup>7</sup> = 128. In signed 8-bit types this position is the sign bit, and <code>x &amp; 0x80</code> is the classic way to test it.</p>",
  },
  {
    type: "fix",
    title: "Identity crisis",
    brief: "Both strings say cat — so why does it print different?",
    code: "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char a[] = \"cat\";\n    char b[] = \"cat\";\n    if (a == b)\n        printf(\"same\\n\");\n    else\n        printf(\"different\\n\");\n    return 0;\n}",
    expect: "same\n",
    hint: "== on arrays compares locations, not letters.",
    expl: "<p><code>a == b</code> compares the addresses of two distinct arrays, which are never equal. String contents are compared with <code>strcmp(a, b)</code>, which returns 0 when they match — so the condition becomes <code>strcmp(a, b) == 0</code>.</p>",
  },
  {
    type: "quiz",
    title: "Bit by bit",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%d %d\\n\", 5 & 3, 5 | 3);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["1 8", "1 7", "1 1", "0 7"],
    a: 1,
    expl: "<p>5 is 101 and 3 is 011. AND keeps the bits set in both (001 = 1); OR keeps the bits set in either (111 = 7). Note that <code>|</code> is not addition — the shared bit is not counted twice.</p>",
  },
  {
    type: "quiz",
    title: "Double crossing",
    code: "#include <stdio.h>\n\nint main(void) {\n    int x = 0;\n    int y = x++ && x++;\n    printf(\"%d %d\\n\", x, y);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["2 0", "2 1", "1 1", "1 0"],
    a: 3,
    expl: "<p>The left <code>x++</code> yields the old value 0, and <code>&amp;&amp;</code> stops as soon as its left side is false — the right <code>x++</code> never runs. So <code>x</code> is incremented once, to 1, and <code>y</code> is 0. This one is well defined: <code>&amp;&amp;</code> sequences its operands.</p>",
  },
  {
    type: "fix",
    title: "Small print",
    brief: "x is 3, so it should print only done — but big shows up too.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int x = 3;\n    if (x > 5);\n    {\n        printf(\"big\\n\");\n    }\n    printf(\"done\\n\");\n    return 0;\n}",
    expect: "done\n",
    hint: "Count the statements the if actually controls.",
    expl: "<p>The stray semicolon is an empty statement — and it is the entire body of the <code>if</code>. The block below is not attached to the condition at all, so it always runs. Delete the semicolon and the block becomes the real body.</p>",
  },
  {
    type: "bits",
    title: "The clock strikes twelve",
    target: 0x0C,
    n: 4,
    brief: "Set the nibble to 12 (0xC).",
    hint: "12 = 8 + 4",
    expl: "<p>1100 — the two high bits of the nibble. Hex digits A through F are simply 10 through 15, so 12 is written C.</p>",
  },
  {
    type: "quiz",
    title: "One small step",
    code: "#include <stdio.h>\n\nint main(void) {\n    int i = 5;\n    int j = i++ + 3;\n    printf(\"%d %d\\n\", i, j);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["6 9", "5 8", "6 8", "5 9"],
    a: 2,
    expl: "<p>Post-increment yields the old value, so <code>j</code> gets 5 + 3 = 8; afterwards <code>i</code> is 6. This is perfectly defined — unlike expressions that write to <code>i</code> twice — because <code>i</code> is modified only once here.</p>",
  },
  {
    type: "fix",
    title: "Lost in translation",
    brief: "It should print 3.140000 — but prints garbage.",
    code: "#include <stdio.h>\n\nint main(void) {\n    double pi = 3.14;\n    printf(\"%d\\n\", pi);\n    return 0;\n}",
    expect: "3.140000\n",
    hint: "Check the conversion specifier against the argument's type.",
    expl: "<p><code>%d</code> makes printf fetch an <code>int</code>, but a <code>double</code> was passed — printf trusts the format string blindly and reads the wrong data. <code>%f</code> matches the argument. Compile with warnings on; the compiler catches every mismatch like this.</p>",
  },
  {
    type: "quiz",
    title: "Three laps later",
    code: "#include <stdio.h>\n\nint main(void) {\n    for (int i = 0; i < 3; i++)\n        ;\n    printf(\"%d\\n\", i);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["3", "compile error", "2", "0"],
    a: 1,
    expl: "<p>A variable declared in the <code>for</code> header lives only inside the loop. By the time <code>printf</code> runs, <code>i</code> no longer exists, so compilation fails with \"'i' undeclared\". Declare <code>i</code> before the loop if you need it afterwards.</p>",
  },
  {
    type: "fix",
    title: "The missing piece",
    brief: "The array sums to 150 — but this prints 140.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int a[] = {10, 20, 30, 40, 50};\n    int sum = 0;\n    for (int i = 1; i < 5; i++)\n        sum += a[i];\n    printf(\"%d\\n\", sum);\n    return 0;\n}",
    expect: "150\n",
    hint: "Which elements does the loop actually visit?",
    expl: "<p>Arrays are indexed from 0, but the loop starts at 1 — so <code>a[0]</code> (the 10) is never added. Starting at <code>i = 0</code> visits all five elements.</p>",
  },
  {
    type: "bits",
    title: "Read it backwards",
    target: 0xA5,
    n: 8,
    brief: "Flip the bits until the byte equals 0xA5.",
    hint: "165 = 128 + 32 + 4 + 1",
    expl: "<p>1010 0101 — a bit-level palindrome: it reads the same in both directions. Nibble by nibble it is A (1010) then 5 (0101), a pattern often used as a memory-test value.</p>",
  },
  {
    type: "quiz",
    title: "Multiplying trouble",
    code: "#include <stdio.h>\n\n#define SQUARE(x) x * x\n\nint main(void) {\n    printf(\"%d\\n\", SQUARE(1 + 2));\n    return 0;\n}",
    q: "What does this print?",
    opts: ["9", "6", "compile error", "5"],
    a: 3,
    expl: "<p>Macros paste text, so the call becomes <code>1 + 2 * 1 + 2</code>, and multiplication binds first: 1 + 2 + 2 = 5, not 9. This is exactly why macro bodies should parenthesize every parameter: <code>((x) * (x))</code>.</p>",
  },
  {
    type: "fix",
    title: "Zero percent",
    brief: "7 out of 10 should be 70 — but this prints 0.",
    code: "#include <stdio.h>\n\nint main(void) {\n    int score = 7, total = 10;\n    printf(\"%d\\n\", score / total * 100);\n    return 0;\n}",
    expect: "70\n",
    hint: "In what order do the division and multiplication happen?",
    expl: "<p><code>score / total</code> runs first, and integer division truncates 0.7 down to 0 — multiplying zero by 100 stays zero. Reordering to <code>score * 100 / total</code> keeps the intermediate value whole until the end.</p>",
  },
  {
    type: "quiz",
    title: "The leftovers",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%d\\n\", -7 % 3);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["2", "-1", "-2", "1"],
    a: 1,
    expl: "<p>Since C99, integer division truncates toward zero and <code>%</code> is defined so that <code>(a/b)*b + a%b == a</code>. With -7 / 3 = -2, the remainder must be -1. In C, the result of <code>%</code> takes the sign of the left operand — unlike the math-class modulo.</p>",
  },
  {
    type: "bits",
    title: "Mask maker",
    target: 0x0F,
    n: 8,
    brief: "Build the classic low-nibble mask 0x0F.",
    hint: "The bottom four, all on.",
    expl: "<p>0000 1111 keeps the low nibble: <code>x &amp; 0x0F</code> clears the top four bits of a byte. Masks like this are how C code extracts bit fields from packed values.</p>",
  },
  {
    type: "fix",
    title: "Half the story",
    brief: "5 divided by 2 is 2.5 — but this prints 2.000000.",
    code: "#include <stdio.h>\n\nint main(void) {\n    double d = 5 / 2;\n    printf(\"%f\\n\", d);\n    return 0;\n}",
    expect: "2.500000\n",
    hint: "The division is finished before the double ever sees it.",
    expl: "<p><code>5 / 2</code> is evaluated entirely in <code>int</code> arithmetic, producing 2, and only that result is converted to 2.0. Making either operand floating point — <code>5.0 / 2</code> — switches the division itself to real arithmetic.</p>",
  },
  {
    type: "quiz",
    title: "Count me in",
    code: "#include <stdio.h>\n\nint main(void) {\n    int a[10];\n    printf(\"%zu\\n\", sizeof(a) / sizeof(a[0]));\n    return 0;\n}",
    q: "What does this print?",
    opts: ["40", "10", "4", "8"],
    a: 1,
    expl: "<p><code>sizeof(a)</code> is the whole array (40 bytes here) and <code>sizeof(a[0])</code> is one element (4 bytes), so the division yields the element count: 10. This idiom works only where the actual array is in scope — never on a pointer parameter.</p>",
  },
  {
    type: "quiz",
    title: "Push the limit",
    code: "#include <stdio.h>\n\nint main(void) {\n    unsigned char c = 255;\n    c++;\n    printf(\"%d\\n\", c);\n    return 0;\n}",
    q: "What does this print?",
    opts: ["0", "256", "-1", "undefined behavior"],
    a: 0,
    expl: "<p>The arithmetic happens in <code>int</code>, giving 256 — but storing it back into an 8-bit <code>unsigned char</code> reduces it modulo 256, leaving 0. For unsigned types this wraparound is fully defined; it is <em>signed</em> overflow that is undefined.</p>",
  },
  {
    type: "quiz",
    title: "Dot dot dot",
    code: "#include <stdio.h>\n\nint main(void) {\n    printf(\"%.3s\\n\", \"hello\");\n    return 0;\n}",
    q: "What does this print?",
    opts: ["hello", "llo", "hel", "compile error"],
    a: 2,
    expl: "<p>For strings, the precision field <code>.3</code> caps how many characters are printed, so only the first three appear. It is a handy trick for printing prefixes — or buffers that are not null-terminated, via <code>%.*s</code>.</p>",
  },
];
